name: "Check PR to master"
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: master
  workflow_dispatch:
jobs:
  run_pre_commit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Checkout repository "
        uses: actions/checkout@v3
      - name: "Setup Python env"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install -r ./back/requirements.txt
        shell: bash
      - run: pre-commit run --all-files --show-diff-on-failure --color=always
        shell: bash